### ISSUE TITLE
support pg_dump

### ISSUE THREAD

**Issue by mnc** [mnc/mozaic#8]
### TODO
- [x] use pg_dump instead of selecting records with SQL
- [ ] convert dump file to AST by parslet gem
- [ ] transform AST by parslet gem
- [ ] put all COPY data into array
